package oci.distribution.client.model.exception

class UnknownErrorException(throwable: Throwable) : Exception("An unknown Exception occurred", throwable)
